Fix urls
ul-fmf/projekt-tomo pull request #265
Opened 2022-11-25 17:22 UTC by schrjako

courses's urls are now grouped to cut down on prefix repetitions. This also fixed some missing prefixes in problem_set urls, which will change some urls and possible bookmarks.

Changed raw strings to normal ones in path objects. The raw specifiier was left over from older django versions with regex paths.

This was talked about at a fmf-club meeting and is now done.

2022-11-28 09:49 UTC, matijapretnar submitted a review, later dismissed
Odlično! Imam tri potencialne izboljšave, ki bi jih samo prediskutiral pred mergeom:

1. Tudi `<int:problem_set_pk>` in podobno se da pridružiti v `path("problem_set/<int:problem_set_pk>/", ...)., da je še manj podvajanja.
2. Težava je pri npr `/problem_set/create/`, ki nima `problem_set_pk`, ampak to bi bilo v resnici bolje `course_urls` in imamo link `course/<int:course_pk>/create_problem/`
3. Ko smo že pri RESTu, bi bili pravi urlji hierarhični, torej tipa `course/123/problem/456/` ali kaj takega.

Pri zadnjih dveh točkah je vprašanje, koliko upamo spreminjati obstoječe URLje. Na dolgi rok bi bilo to verjetno dobro narediti.

2022-11-28 13:48 UTC, matijapretnar commented on web/courses/views.py
> +    pk_url_kwarg = "course_pk"
A je to sigurno pravilno, a naj ne bi `pk_url_kwarg` povedal, pod katerim imenom se skriva PK od `ProblemSeta`, ki ga popravljamo?

2022-11-28 13:53 UTC, matijapretnar requested changes

2022-11-28 13:53 UTC, matijapretnar commented on web/courses/urls.py
> +    path(
A ne spada to pod `problem_set_views`?

2022-11-28 13:53 UTC, matijapretnar commented on web/courses/views.py
> +    pk_url_kwarg = "course_pk"
A je to sigurno pravilno, a naj ne bi `pk_url_kwarg` povedal, pod katerim imenom se skriva PK od `ProblemSeta`, ki ga popravljamo?

2022-11-29 15:17 UTC, schrjako commented
Imate prav. Nisem si vzel dovolj casa in sem prevec na hitro ter na pamet naredil stvari. Sedaj bi morale biti v redu

2022-11-29 22:29 UTC, matijapretnar commented on web/courses/urls.py
> +    path(
Tole je letelo na `update_problem_set`, ki ima pk.

2022-11-29 22:30 UTC, matijapretnar commented on web/courses/urls.py
> +        "update_problem_set/",
`update/`

2022-11-29 22:31 UTC, matijapretnar commented on web/courses/urls.py
> +        "delete_problem_set/",
`delete/`

2022-12-01 15:31 UTC, schrjako commented on web/courses/urls.py
> +        "delete_problem_set/",
d1ad7782d841a3c2e808c350554ceaf7ba169d60

2022-12-01 15:31 UTC, schrjako commented on web/courses/urls.py
> +        "update_problem_set/",
d1ad7782d841a3c2e808c350554ceaf7ba169d60

2022-12-02 09:10 UTC, matijapretnar submitted a review, later dismissed
A bi v sklopu tega PRa naredili še prenos `problem_set_urls` in podobno `group_urls` pod `course_urls`, da se samo enkrat spreminjajo URLji?

2022-12-02 15:19 UTC, schrjako commented
Meni bi se zdelo smiselno, nimam pa pojma kdaj bom za to nasel cas. Ko bo pa bo.

2022-12-05 07:33 UTC, matijapretnar commented
Ni problema, lahko jaz dokončam.

2022-12-16 12:34 UTC, matijapretnar approved these changes
Ok, po mojem je zdaj v redu. Veliko dela in hrupa za nič, ampak smo se vsaj kaj naučili :)

2023-01-10 09:11 UTC, merged