Vidnost nalog
ul-fmf/projekt-tomo pull request #289
Opened 2023-02-28 16:15 UTC by schrjako

Manjkajo se prevodi dolocenih dodanih besedil, vendar ne vem kako jih dodati. Tezavo opisal v #266

2023-02-28 21:32 UTC, schrjako commented
Closes #266

2023-03-01 13:49 UTC, matijapretnar requested changes
Jaz bi prikaz in urejanje vidnosti nalog imel samo v spletnem vmesniku, v datotekah pa ne, sicer bo zmeda.

2023-03-08 09:55 UTC, matijapretnar commented
Tisti del, s katerim sem se strinjal, sem že dal na `master`. Vprašanje je, kaj naredimo s prevodi - to je po mojem ločen issue?

2023-03-08 14:12 UTC, schrjako commented
Ali ne bi bilo smiselno, da prevodi stvari iz tega pr-ja so v tem pr-ju?

2023-03-08 14:27 UTC, matijapretnar commented
Ja, se strinjam. Težava je, da že nekaj časa nisem delal s prevodi in ne vem, ali je vzrok težave s prevodi:
1. sistemski, torej da infrastruktura za prevode ne dela pravilno
2. v tem, da ste v tem PRju nekaj napisali narobe.
V vsakem primeru je treba odpreti ločen issue z dokumentacijo prevodov, … (to delam ravnokar - #290), v primeru 2. pa je poleg tega je pa treba ugotoviti, ali ta PR potrebuje še kaj dodatnega dela ali ne.

Glede na to, da so prevodi trenutno itak bolj zmedeni, to ne bi smelo ustaviti PRja, zato predlagam, da se ga sprejme, ko se pobriše vidnost nalog iz datotek za urejanje (ali me prepriča nasprotno). Še to, kakšna je logika pri commitu [Add not visible problems to problem_set statistics](https://github.com/ul-fmf/projekt-tomo/pull/289/commits/475744396984983b727e7b63c702eb355fbe125c) - je to fixup prvotnega PRja ali kaj drugega?

2023-03-08 15:19 UTC, schrjako commented
Meni se zdi smiselno, da bi se vidnost naloge videlo tudi v datotekah. Moram pa priznat da ne poznam tomo-workflowa kot ucitelj sploh in v bistvu nimam pojma, kaj je tle pravi odgovor.

2023-03-08 15:24 UTC, matijapretnar commented
Sem še malo razmislil. Ko bomo enkrat naredili #286, bo vidnost na `ProblemInstance`, datoteke za urejanje pa na `Problem`, tako da bomo takrat to tako ali tako morali dati ven.

2023-03-08 18:18 UTC, schrjako commented
Je smiselno, imate prav.

2023-03-09 10:06 UTC, matijapretnar approved these changes

2023-03-09 10:06 UTC, merged